version: '3'
services:
  app:
    container_name: ms_users
    image: node:10-alpine
    restart: always
    command: sh -c "npm install && npm run start"
    working_dir: /var/www/ms1
    volumes:
      - ".:/var/www/ms1"
    ports:
      - "${API_PORT}:${API_PORT}"
    links:
      - redis
      - mongo
  mongo:
    container_name: Users_MongoDB
    image: 'mongo:4.0.11'
    command: mongod --port ${MONGODB_PORT}
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
  redis:
    container_name: redis
    image: 'redis:5.0.5'
    command: redis-server --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"